=== 404NotFoundx/ormtools/standard/minipika-configruation-standard.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  Copyright (C) 2020 tiansheng All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!ELEMENT minipika (default?, datasources, plugins?)>

<!ELEMENT datasources (master)>
<!ATTLIST datasources
using CDATA
>

<!ELEMENT properties (printExecutingLog?)>

<!ELEMENT printExecutingLog EMPTY>

<!ELEMENT master (url, driver, username, password)>
<!ATTLIST master
type CDATA
>

<!ELEMENT slaves (url, driver, username, password)>
<!ATTLIST slaves
type CDATA
>

<!ELEMENT property EMPTY>
<!ATTLIST property
key CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT default (datasource)>

<!ELEMENT datasource EMPTY>

<!ELEMENT url (property?)>
<!ATTLIST url
value CDATA #REQUIRED
>

<!ELEMENT driver EMPTY>
<!ATTLIST driver
value CDATA #REQUIRED
>

<!ELEMENT username EMPTY>
<!ATTLIST username
value CDATA #REQUIRED
>

<!ELEMENT password EMPTY>
<!ATTLIST password
value CDATA #REQUIRED
>

<!ELEMENT plugins EMPTY>

=== 404NotFoundx/ormtools/src/main/test/resources/minipika-copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minipika SYSTEM
        "https://gitee.com/appcuver/minipika/blob/master/standard/minipika-configruation-standard.dtd">
<minipika>
  
  <!-- 支持全局使用的属性配置, 这个大家都清楚就不再赘述了 -->
  <properties>
    <printExecutingLog>false</printExecutingLog>
  </properties>
  
  <!--
    配置数据源.
    如果不想用默认数据源的话可以在datasources标签中添加using属性，并设置你的数据源类的路径即可.
    像这样：<datasources using="com.alibaba.druid.pool.DruidDataSource">配置德鲁伊的数据源

    如果存在多个数据源的话也可以配置主从数据源, 还可以将每个数据源抽出来做读写分离
    主从数据源可以是不同类型的数据库, 可以是MYSQL, 可以是ORACLE等不同的数据库, 只需要在数据源的标签上
    添加一个type即可: <master type="MYSQL"> 不分大小写

    如果要设置单个数据源的任务的话可以使用task="READ"或者是task="WRITE"来设置单个数据源的作业
    示例:
      // 将主库设置为只读
      <master type="MYSQL" task="READ">
        省略部分代码...
      </master>

      // 将从库设置为只写
      <slaves type="MYSQL" task="WRITE">
        省略部分代码...
      </slaves
   -->
  <datasources>
    <master type="MYSQL" task="READ">
      <!-- 设置JDBC URL以及URL参数 -->
      <url value="jdbc:mysql://127.0.0.1:3306/test">
        <property key="useSSL" value="false"/>
        <property key="useUnicode" value="true"/>
        <property key="characterEncoding" value="utf-8"/>
        <property key="serverTimezone" value="GMT"/>
      </url>
      <driver value="com.mysql.cj.jdbc.Driver"/>
      <username value="root"/>
      <password value="root"/>
    </master>
  </datasources>

</minipika>
